name: Android NDK Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c

    - name: Compile C++ Code (Force Root Structure)
      run: |
        # Local runner workflow ke andar ek real jni folder mimic karte hain
        mkdir -p fake_project/jni
        
        # .github folder ko chhodkar baki saari main files ko fake jni me move karo
        find . -maxdepth 1 ! -name '.' ! -name '.github' ! -name 'fake_project' -exec cp -r {} fake_project/jni/ \;
        
        # Ab structure perfect hai, direct run karo!
        cd fake_project/jni
        ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=Android.mk NDK_APPLICATION_MK=Application.mk APP_ABI=arm64-v8a

    - name: Upload Compiled .so File
      uses: actions/upload-artifact@v4
      with:
        name: Compiled-SO-Binary
        path: '**/libs/arm64-v8a/*.so'
        
